export { Calendar } from '@/assets/icon-components/calendar'
export { Check } from '@/assets/icon-components/check'
export { ChevronLeft } from '@/assets/icon-components/chevron-left'
export { ChevronRight } from '@/assets/icon-components/chevron-right'
export { Copy } from '@/assets/icon-components/copy'
export { CreditCard } from '@/assets/icon-components/credit-card'
export { DirectionUpRight } from '@/assets/icon-components/direction-up-right'
export { EditPen } from '@/assets/icon-components/edit-pen'
export { Filter } from '@/assets/icon-components/filter'
export { Minus } from '@/assets/icon-components/minus'
export { Multiply } from '@/assets/icon-components/multiply'
export { NoteWithText } from '@/assets/icon-components/note-with-text'
export { Plus } from '@/assets/icon-components/plus'
export { Search } from '@/assets/icon-components/search'
export { Shop } from '@/assets/icon-components/shop'
export { Tag } from '@/assets/icon-components/tag'
export { Trash2 } from '@/assets/icon-components/trash-2'

export { Icon } from './Icon'
export { iconRegistry } from './registry'
export type { IconName, IconProps } from './types'
